- src: https://github.com/thevictorgreen/devopsify-ansible-role-aptly
  version: v0.1.0
  name: aptly
- src: https://github.com/thevictorgreen/devopsify-ansible-role-arangodbmaster
  version: v0.1.1
  name: arangodbmaster
- src: https://github.com/thevictorgreen/devopsify-ansible-role-arangodbnode
  version: v0.1.1
  name: arangodbnode
- src: https://github.com/thevictorgreen/devopsify-ansible-role-chefclient
  version: v0.1.3
  name: chefclient
- src: https://github.com/thevictorgreen/devopsify-ansible-role-chefserver
  version: v0.1.1
  name: chefserver
- src: https://github.com/thevictorgreen/devopsify-ansible-role-chefworkstation
  version: v0.1.1
  name: chefworkstation
- src: https://github.com/thevictorgreen/devopsify-ansible-role-common
  version: v0.1.2
  name: common
- src: https://github.com/thevictorgreen/devopsify-ansible-role-common-centos
  version: v0.1.0
  name: commoncentos
- src: https://github.com/thevictorgreen/devopsify-ansible-role-common-ubuntu
  version: v0.1.0
  name: commonubuntu
- src: https://github.com/thevictorgreen/devopsify-ansible-role-consul
  version: v0.1.0
  name: consul
- src: https://github.com/thevictorgreen/devopsify-ansible-role-dnsforwarder
  version: v0.1.4
  name: dnsforwarder
- src: https://github.com/thevictorgreen/devopsify-ansible-role-elasticsearchmaster
  version: v0.1.2
  name: elasticsearchmaster
- src: https://github.com/thevictorgreen/devopsify-ansible-role-elasticsearchnode
  version: v0.1.0
  name: elasticsearchnode
- src: https://github.com/thevictorgreen/devopsify-ansible-role-flink
  version: v0.1.0
  name: flink
- src: https://github.com/thevictorgreen/devopsify-ansible-role-gitlab
  version: v0.1.1
  name: gitlab
- src: https://github.com/thevictorgreen/devopsify-ansible-role-hadoop
  version: v0.1.1
  name: hadoop
- src: https://github.com/thevictorgreen/devopsify-ansible-role-influxdb
  version: v0.1.2
  name: influxdb
- src: https://github.com/thevictorgreen/devopsify-ansible-role-ipa
  version: v0.1.0
  name: ipa
- src: https://github.com/thevictorgreen/devopsify-ansible-role-jenkinsmaster
  version: v0.1.0
  name: jenkinsmaster
- src: https://github.com/thevictorgreen/devopsify-ansible-role-jenkinsnode
  version: v0.1.0
  name: jenkinsnode
- src: https://github.com/thevictorgreen/devopsify-ansible-role-kafka
  version: v0.1.0
  name: kafka
- src: https://github.com/thevictorgreen/devopsify-ansible-role-kubernetes
  version: v0.1.1
  name: kubernetes
- src: https://github.com/thevictorgreen/devopsify-ansible-role-nginx
  version: v0.1.1
  name: nginx
- src: https://github.com/thevictorgreen/devopsify-ansible-role-nifi
  version: v0.1.0
  name: nifi
- src: https://github.com/thevictorgreen/devopsify-ansible-role-openvpn
  version: v0.1.3
  name: openvpn
- src: https://github.com/thevictorgreen/devopsify-ansible-role-pki
  version: v0.1.1
  name: pki
- src: https://github.com/thevictorgreen/devopsify-ansible-role-rundeck
  version: v0.1.3
  name: rundeck
- src: https://github.com/thevictorgreen/devopsify-ansible-role-sonarqube
  version: v0.1.0
  name: sonarqube
- src: https://github.com/thevictorgreen/devopsify-ansible-role-spark
  version: v0.1.0
  name: spark
- src: https://github.com/thevictorgreen/devopsify-ansible-role-vault
  version: v0.1.1
  name: vault
- src: https://github.com/thevictorgreen/devopsify-ansible-role-zookeeper
  version: v0.1.1
  name: zookeeper
